### ISSUE TITLE
[Dohyun] 헤더 및 메인페이지

### ISSUE THREAD

**Issue by DoDOhyeon** [thgus5335/RollingProject#13]
## 이슈내용

- [x] 메인페이지 UI 구현, 사이즈 조절이 필요할거같습니다.
- [x] 모바일, 태블릿 반응형 디자인 구현

## TODO
- [x] 메인페이지 사이즈 조정
- [ ] 이모지 기능 추가
- [ ] 카카오톡 공유기능 추가
