### ISSUE TITLE
[Hyunjun] 메시지 생성 페이지

### ISSUE THREAD

**Issue by hyunjun9788** [thgus5335/RollingProject#6]
## 이슈내용

- [x] 프로필 이미지 선택할 때, 클릭한 이미지에 대해 테두리 선을 추가하고 싶어 구현 중인데 시간이 많이 소요되고 있습니다!
- [x] 리렌더링 이슈 해결해야 될 것 같습니다!

## TODO
- [x] 모바일, 태블릿 반응형 디자인 구현
- [x] 프로필 이미지 테두리 선 추가 기능 구현
- [x] form 태그 활용하여 생성하기 버튼 클릭 시 데이터 전송
- [x] API 작업
